ShoppingCartMvc/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;



using ShoppingCartMvc.Models;
using ShopingCartEF;

namespace ShoppingCartMvc.Controllers
{
    public class CheckoutController : Controller
    {
        //
        // GET: /Checkout/
        public ActionResult Index()
        {

            var db = new ShoppingCartEntities();
            var payments = db.PaymenMethods.ToList();
            ViewBag.Payments = payments;
            return View(GetCart());
        }
        public MyCart GetCart()
        {
            MyCart cart = (MyCart)Session["Cart"];
            if (cart == null)
            {
                cart = new MyCart();
                Session["Cart"] = cart;
            }
            return cart;
        }
        public ActionResult Checkout()
        {


            return View(new Orther { });
        }
        [HttpPost]
        public ActionResult AddToOrder(int PaymentMethod)
        {
            var db = new ShoppingCartEntities();
            if (GetCart() != null)
            {
                var orther = new Orther
                {
                    Amout = GetCart().SubTotal(),
                    DateOrdered = DateTime.Now,
                    Status = "Chưa thanh toán",
                    PaymenMethodsID = PaymentMethod

                };
                db.Orthers.Add(orther);
                db.SaveChanges();
                Session.Abandon();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

ShoppingCartMvc/Views/Checkout/Index.cshtml
@model ShoppingCartMvc.Models.MyCart
@{
    ViewBag.Title = "Index";
}

<section id="cart_items">
    <div class="container">
        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li><a href="#">Home</a></li>
                <li class="active">Check out</li>
            </ol>
        </div><!--/breadcrums-->

        <div class="step-one">
            <h2 class="heading">Bước 1</h2>
        </div>
        <div class="checkout-options">
            <h3>Khách hàng mới</h3>
            @*<p>Chọn cách thanh toán</p>*@
            <ul class="nav">
                <li>
                    <label><input type="checkbox">Đăng ký tài khoản</label>
                </li>
                <li>
                    <label><input type="checkbox">Sử dụng tài khoản khách</label>
                </li>
                <li>
                    <a href=""><i class="fa fa-times"></i>Thoát</a>
                </li>
            </ul>
        </div><!--/checkout-options-->

        <div class="register-req">
            <p>Please use Register And Checkout to easily get access to your order history, or use Checkout as Guest</p>
        </div><!--/register-req-->

        <div class="shopper-informations">
            <div class="row">
                <div class="col-sm-3">
                    <div class="shopper-info">
                        <p>Shopper Information</p>
                        <form>
                            <input type="text" placeholder="Tên hiển thị">
                            <input type="text" placeholder="Tên đăng nhập">
                            <input type="email" placeholder="Địa chỉ email">
                            <input type="password" placeholder="Mật khẩu">
                            <input type="password" placeholder="Xác nhận lại mật khẩu">
                        </form>
                        <a class="btn btn-primary" href="">Get Quotes</a>
                        <a class="btn btn-primary" href="">Tiếp tục</a>
                    </div>
                </div>
                @*<div class="col-sm-5 clearfix">
                    <div class="bill-to">
                        <p>Bill To</p>
                        <div class="form-one">
                            <form>
                                <input type="text" placeholder="Company Name">
                                <input type="text" placeholder="Email*">
                                <input type="text" placeholder="Title">
                                <input type="text" placeholder="First Name *">
                                <input type="text" placeholder="Middle Name">
                                <input type="text" placeholder="Last Name *">
                                <input type="text" placeholder="Address 1 *">
                                <input type="text" placeholder="Address 2">
                            </form>
                        </div>
                        <div class="form-two">
                            <form>
                                <input type="text" placeholder="Zip / Postal Code *">
                                <select>
                                    <option>-- Country --</option>
                                    <option>United States</option>
                                    <option>Bangladesh</option>
                                    <option>UK</option>
                                    <option>India</option>
                                    <option>Pakistan</option>
                                    <option>Ucrane</option>
                                    <option>Canada</option>
                                    <option>Dubai</option>
                                </select>
                                <select>
                                    <option>-- State / Province / Region --</option>
                                    <option>United States</option>
                                    <option>Bangladesh</option>
                                    <option>UK</option>
                                    <option>India</option>
                                    <option>Pakistan</option>
                                    <option>Ucrane</option>
                                    <option>Canada</option>
                                    <option>Dubai</option>
                                </select>
                                <input type="password" placeholder="Confirm password">
                                <input type="text" placeholder="Phone *">
                                <input type="text" placeholder="Mobile Phone">
                                <input type="text" placeholder="Fax">
                            </form>
                        </div>
                    </div>
                </div>*@
                <div class="col-sm-4">
                    <div class="order-message">
                        <p>Thông tin bổ sung</p>
                        <textarea name="message" placeholder="Địa chỉ, số điện thoại khác..." rows="16"></textarea>
                        <label><input type="checkbox"> Giao hàng tới địa chỉ trên</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="review-payment">
            <h2> Đơn hàng</h2>
        </div>

        <div class="table-responsive cart_info">
            <table class="table table-condensed">
                <thead>
                    <tr class="cart_menu">
                        <td class="image">Item</td>
                        <td class="description"></td>
                        <td class="price">Price</td>
                        <td class="quantity">Quantity</td>
                        <td class="total">Total</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.MyCarts)
                    {
                        <tr>
                            <td class="cart_product">
                                <a href=""><img src="/images/cart/one.png" alt=""></a>
                            </td>
                            <td class="cart_description">
                                <h4><a href="">@item.Product.Description</a></h4>
                                <p>Web ID: 1089772</p>
                            </td>
                            <td class="cart_price">
                                <p>@item.Product.Price</p>
                            </td>
                            <td class="">
                                <div class="cart_quantity_button">
                                    <a class="cart_quantity_up" href=""> + </a>
                                    <input class="cart_quantity_input" type="text" name="quantity" value="@item.Quantity" autocomplete="off" size="2">
                                    <a class="cart_quantity_down" href=""> - </a>
                                </div>
                            </td>
                            <td class="">
                                <p class="cart_total_price">@item.Total</p>
                            </td>
                            <td class="cart_delete">
                                <a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
                            </td>
                        </tr>
                    }
                   

                    <tr>
                        <td colspan="4">&nbsp;</td>
                        <td colspan="2">
                            <table class="table table-condensed total-result">
                                <tbody>
                                    <tr>
                                        <td>Tổng tiền trên giỏ hàng</td>
                                        <td>$59</td>
                                    </tr>
                                    @*<tr>
                                        <td>Exo Tax</td>
                                        <td>$2</td>
                                    </tr>*@
                                    <tr class="shipping-cost">
                                        <td>Phí giao hàng</td>
                                        <td>Free</td>
                                    </tr>
                                    <tr>
                                        <td>Thành tiền</td>
                                        <td><span>$61</span></td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
      
        <div class="Phương thức hành toán">
            


             

            @using (Html.BeginForm("AddToOrder", "Checkout", FormMethod.Post))
            {

                <label><input type="checkbox"> Thanh toán qua ngân hàng</label>
                <select name="PaymentMethod" id="PaymentMethod">

                    @foreach (var item in ViewBag.Payments)
                    {

                        <option value="@item.PaymenMethodsID">@item.Name</option>

                    }
                </select>

                <button button type="submit" class="btn btn-default check_out" href="">Thanh toán</button>

            }
        </div>

    </div>
</section>