ShoppingCartMvc/Controllers/SendMailController.cs
using ShoppingCartMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoppingCartMvc.Controllers
{
    public class SendMailController : Controller
    {
        // GET: SendMailController
        public ActionResult Index()
        {
            var model = new ContactModel();
            return View(model);
        }
        [HttpPost]
        public ActionResult Index(ContactModel model)
        {
            if (ModelState.IsValid)
            {
                string smtpUserName = "luckyboyuit06@gmail.com";
                string smtpPassword = "fxiabhvdgejdcexf";
                string smtpHost = "smtp.gmail.com";
                int smtpPort = 25;

                string emailTo = "luckyboyuit06@gmail.com"; // Khi có liên hệ sẽ gửi về thư của mình
                string subject = model.Subject;
                string body = string.Format("Bạn vừa nhận được liên hệ từ: <b>{0}</b><br/>Email: {1}<br/>Nội dung: </br>{2}",
                    model.UserName, model.Email, model.Message);

                EmailService service = new EmailService();

                bool kq = service.Send(smtpUserName, smtpPassword, smtpHost, smtpPort,
                    emailTo, subject, body);

                if (kq) ModelState.AddModelError("", "Cảm ơn bạn đã liên hệ với chúng tôi.");
                else ModelState.AddModelError("", "Gửi tin nhắn thất bại, vui lòng thử lại.");
            }
            return View(model);
        }
    }
}

ShoppingCartMvc/Views/SendMail/Index.cshtml
@model ShoppingCartMvc.Models.ContactModel
@{
    ViewBag.Title = "Index";
}
<section id="form">
    <!--form-->
    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-1">
                <div class="login-form">
                    <!--login form-->
                    <h2>Nội dung email</h2>
                   @using (Html.BeginForm("Index", "SendMail", FormMethod.Post))
                   {
                        @Html.ValidationSummary(true)
                       // @Html.HiddenFor(model => model.UserName)
                        //@Html.HiddenFor(model => model.Email)
                        @*@Html.HiddenFor(model => model.Subject)
                        @Html.HiddenFor(model => model.Message)*@
                        @Html.AntiForgeryToken()

                        @Html.TextBoxFor(model => model.UserName, htmlAttributes: new { @placeholder = "Tên đăng nhập" })
                        @Html.TextBoxFor(model => model.Email, htmlAttributes: new { @placeholder = "Địa chỉ email" })
                        @Html.TextBoxFor(model => model.Subject, htmlAttributes: new { @placeholder = "Tiều đề" })
                        @Html.TextAreaFor(model => model.Message,10,15, htmlAttributes: new { @placeholder = "Nội dung" })
                       
                        <button type="submit" class="btn btn-default">Gửi</button>

                   }
                </div><!--/login form-->
            </div>
          
          
        </div>
    </div>
</section>
</html>