ShoppingCartMvc/Areas/Admin/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopingCartEF;
using PagedList;

namespace ShoppingCartMvc.Areas.Admin.Controllers
{
    public class CustomersController : Controller
    {
        private ShoppingCartEntities db = new ShoppingCartEntities();

        // GET: Admin/Customers
        public ActionResult Index(int?page)
        {
            int pageSize = 4; // day la so item tren 1 trang
            int pageNumber = (page ?? 1); // day la trang thu X
            var list = from s in db.Customers
                       select s;
            return View(list.ToList().ToPagedList(pageNumber, pageSize)); // return cai gi thi view tuong ung cai do
        }

        // GET: Admin/Customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Admin/Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CustomerID,Name,Email,Password,Phone,DOB,Adress")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Admin/Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Admin/Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CustomerID,Name,Email,Password,Phone,DOB,Adress")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Admin/Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Admin/Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShoppingCartMvc/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopingCartEF;
using ShoppingCartMvc.Filters;
using System.Text;
using System.Security.Cryptography;
using Facebook;
using System.Configuration;

namespace ShoppingCartMvc.Controllers
{
    public class CustomerController : Controller
    {
        private ShoppingCartEntities db = new ShoppingCartEntities();


        // Trang ca nhan: MyProfile
        // Trang Login
        // Trang Register
        // Trang MyOrder
        // Trang ChangePassword,
        // Trang FogotPassword

        // GET: /Customer/
        [CustomerLoginFilter]
        public ActionResult Index()
        {
            
            return View();
        }
      
        [HttpGet]
        public JsonResult CheckEmailExists(string email)
        {
            var exists = db.Customers.Any(x => x.Email.Equals(email.Trim()));
            return Json(exists, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Register()
        {
            // kiem tra dang nhap ahay chua
            if (Session["Customer"] == null)
            {
                return View(new Customer { });
            }
            return RedirectToAction("Index", "Home");

        }
        // GET: /Account/ConfirmEmail 
        [AllowAnonymous]
        public  ActionResult ConfirmEmail(int token, string email)
        {
            var v = db.Customers.Where(a => a.CustomerID.Equals(token)).FirstOrDefault();
            if (v != null)
            {
                if (v.Email == email)
                {
                    return RedirectToAction("Index", "Customer");
                }
                else
                {
                    return RedirectToAction("Confirm", "Customer", new { Email = v.Email });
                }
            }
            else
            {
                return RedirectToAction("Confirm", "Customer", new { Email = "" });
            }

        }

        public static string EncodeMD52(string stringValue)
        {
            Byte[] original;
            Byte[] encode;
            MD5 md5 = new MD5CryptoServiceProvider();
            original = ASCIIEncoding.Default.GetBytes(stringValue);
            encode = md5.ComputeHash(original);
            return BitConverter.ToString(encode);
        }

        private string Encryptdata(string password)
        {
            string strmsg = string.Empty;
            byte[] encode = new byte[password.Length];
            encode = Encoding.UTF8.GetBytes(password);
            strmsg = Convert.ToBase64String(encode);
            return strmsg;
        }
        private string Decryptdata(string encryptpwd)
        {
            string decryptpwd = string.Empty;
            UTF8Encoding encodepwd = new UTF8Encoding();
            Decoder Decode = encodepwd.GetDecoder();
            byte[] todecode_byte = Convert.FromBase64String(encryptpwd);
            int charCount = Decode.GetCharCount(todecode_byte, 0, todecode_byte.Length);
            char[] decoded_char = new char[charCount];
            Decode.GetChars(todecode_byte, 0, todecode_byte.Length, decoded_char, 0);
            decryptpwd = new String(decoded_char);
            return decryptpwd;
        }
        // Action nayxu ly, khong hien thi
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(Customer customer)
        {
            if (ModelState.IsValid)
            {
                using (ShoppingCartEntities db = new ShoppingCartEntities())
                {
                    customer.Password = EncodeMD52(customer.Password);
                    var isEmail = db.Customers.FirstOrDefault(a => a.Email.Equals(customer.Email));
                    if  (isEmail != null)
                    {
                        db.Customers.Add(customer);
                        int result = db.SaveChanges();
                        if (result > 0)
                        {
                            System.Net.Mail.MailMessage m = new System.Net.Mail.MailMessage(
                                new System.Net.Mail.MailAddress("luckyboyuit06@gmail.com", "Web Registration"),
                                new System.Net.Mail.MailAddress(customer.Email));
                            m.Subject = "Email confirmation";
                            m.Body = string.Format("Dear {0}<BR/>Thank you for your registration, please click on the below link to comlete your registration: <a href=\"{1}\" title=\"User Email Confirm\">{1}</a>", customer.Email, Url.Action("ConfirmEmail", "Customer", new { Token = customer.CustomerID, Email = customer.Email }, Request.Url.Scheme));
                            m.IsBodyHtml = true;
                            System.Net.Mail.SmtpClient smtp = new System.Net.Mail.SmtpClient("smtp.gmail.com");
                            smtp.Credentials = new System.Net.NetworkCredential("luckyboyuit06@gmail.com", "fxiabhvdgejdcexf");
                            smtp.EnableSsl = true;
                            smtp.Send(m);
                            return RedirectToAction("Confirm", "Customer", new { Email = customer.Email });
                        }
                    }
                   
                    else
                    {
                        
                    }

                }
            }

            return RedirectToAction("Index");
        }
        [AllowAnonymous]
        public ActionResult Confirm(string Email)
        {
            ViewBag.Email = Email; return View();
        }
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }
        //private Uri 

        //{
        //    get
        //    {
        //        var uriBuilder = new UriBuilder(Request.Url);
        //        uriBuilder.Query = null;
        //        uriBuilder.Fragment = null;
        //        uriBuilder.Path = Url.Action("FacebookCallback");
        //        return uriBuilder.Uri;

        //    }
        //}
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult FacebookCallback(string code, string returnUrl)
        //{
        //    var fb = new FacebookClient();
        //    dynamic result = fb.Post("oauth/access_token",
        //        new
        //        {
        //            client_id = ConfigurationManager.AppSettings["FbAppId"],
        //            client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
        //            redirect_uri = RedirectUri.AbsoluteUri,
        //            code = code
        //        });
        //    var accessToken = result.access_token;
        //    if (!string.IsNullOrEmpty(accessToken))
        //    {
        //        fb.AccessToken = accessToken;
        //        dynamic me = fb.Get("me?fields= first_name,middle_name,last_name, id,email");
        //        string email = me.email;
        //        string userName = me.email;
        //        string firstName = me.first_name;
        //        string middleName = me.middle_name;
        //        string lastName = me.last_name;
        //        using (ShoppingCartEntities db = new ShoppingCartEntities())
        //        {
        //            var customer = new Customer();
        //            customer.Email = email;
        //            customer.Name = firstName + "" + middleName + "" + lastName;
        //            var isEmail = db.Customers.FirstOrDefault(a => a.Email.Equals(email));
        //            if (isEmail != null)
        //            {
        //                db.Customers.Add(customer);
        //                var saveChange = db.SaveChanges();
        //                if (saveChange > 0)
        //                {
        //                    Session["Customer"] = saveChange;
        //                    Session["Login"] = true;
        //                    return RedirectToLocal(returnUrl);
        //                }
        //                else
        //                {
        //                    ModelState.AddModelError("", "Invalid username or password.");
        //                }
        //            }
        //        }
        //    }
        //    return RedirectToLocal(returnUrl);
        //}
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult LoginFacebook()
        //{
        //    var fb = new FacebookClient();
        //    var loginUrl = fb.GetLoginUrl(
        //        new
        //        {
        //            client_id = ConfigurationManager.AppSettings["FbAppId"],
        //            client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
        //            redirect_uri = RedirectUri.AbsoluteUri,
        //            response_type = "code",
        //            scope = "email"
        //        });
        //    return Redirect(loginUrl.AbsoluteUri);
        //}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Customer cus, string returnUrl)
        {           
            using (ShoppingCartEntities db = new ShoppingCartEntities())
            {
                cus.Password = EncodeMD52(cus.Password);
                var v = db.Customers.Where(a => a.Email.Equals(cus.Email) && a.Password.Equals(cus.Password)).FirstOrDefault();
                if (v != null)
                {
                    Session["Customer"] = v;
                    Session["UserName"] = v.Name.ToString();
                    Session["Login"] = true;
                    return RedirectToLocal(returnUrl);
                }
                else
                {
                    ModelState.AddModelError("", "Invalid username or password.");
                }
            }

            return View(cus);

        }
        private ActionResult RedirectToLocal(string returnUrl)
        {

ShoppingCartMvc/Areas/Admin/Views/Customers/Create.cshtml
@model ShopingCartEF.Customer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShoppingCartMvc/Areas/Admin/Views/Customers/Delete.cshtml
@model ShopingCartEF.Customer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adress)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShoppingCartMvc/Areas/Admin/Views/Customers/Details.cshtml
@model ShopingCartEF.Customer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adress)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CustomerID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ShoppingCartMvc/Areas/Admin/Views/Customers/Index.cshtml
@model PagedList.IPagedList<ShopingCartEF.Customer>

@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
}
<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>
        <a href="@Url.Action("index","Home")">Trang chủ</a>
        <i class="icon-angle-right"></i>
    </li>
    <li><a href="@Url.Action("index", "Customers")"> hàng</a></li>
</ul>

<div class="row-fluid sortable ui-sortable">
    <div class="box span12">
        <div class="box-header" data-original-title="">
            <h2><i class="halflings-icon user"></i><span class="break"></span>Danh mục</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <div id="1DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                <div class="row-fluid">
                    <div class="span6">
                        <div class="dataTables_length" id="DataTables_Table_0_length">
                            <label>
                                <select aria-controls="DataTables_Table_0" size="1" name="DataTables_Table_0_length">
                                    <option selected="selected" value="10">10</option>
                                    <option value="25">25</option>
                                    <option value="50">50</option>
                                    <option value="100">100</option>
                                </select> records per page
                            </label>
                        </div>
                    </div><div class="span6">
                        <div id="DataTables_Table_01_filter" class="dataTables_filter">
                            <label>Search: <input aria-controls="DataTables_Table_0" type="text"></label>
                        </div>
                    </div>
                </div>
                >

                <table aria-describedby="DataTables_Table_0_info1" id="DataTables_Table_01" class="table table-striped table-bordered bootstrap-datatable datatable dataTable">
                    <thead>
                        <tr role="row">

                            <th aria-label="Username: activate to sort column descending" aria-sort="ascending" style="width: 171px;" colspan="1" rowspan="1" aria-controls="DataTables_Table_0" tabindex="0" role="columnheader" class="sorting_asc">
                                Username
                            </th>
                            <th aria-label="Date registered: activate to sort column ascending" style="width: 248px;" colspan="1" rowspan="1" aria-controls="DataTables_Table_0" tabindex="0" role="columnheader" class="sorting">
                                Email @*Date registered*@
                            </th>
                            <th aria-label="Role: activate to sort column ascending" style="width: 137px;" colspan="1" rowspan="1" aria-controls="DataTables_Table_0" tabindex="0" role="columnheader" class="sorting">
                                Password
                            </th>
                            <th aria-label="Role: activate to sort column ascending" style="width: 137px;" colspan="1" rowspan="1" aria-controls="DataTables_Table_0" tabindex="0" role="columnheader" class="sorting">
                                Phone
                            </th>
                            <th aria-label="Status: activate to sort column ascending" style="width: 144px;" colspan="1" rowspan="1" aria-controls="DataTables_Table_0" tabindex="0" role="columnheader" class="sorting">
                                DOB
                            </th>
                            <th aria-label="Actions: activate to sort column ascending" style="width: 288px;" colspan="1" rowspan="1" aria-controls="DataTables_Table_0" tabindex="0" role="columnheader" class="sorting">
                                Actions
                            </th>

                        </tr>
                    </thead>

                    <tbody aria-relevant="all" aria-live="polite" role="alert">
                        @foreach (var item in Model)
                        {
                            <tr class="odd">

                                <td class="  sorting_1">
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td class="center ">

                                    @Html.DisplayFor(modelItem => item.Email)
                                </td>
                                <td class="  sorting_1">
                                    @Html.DisplayFor(modelItem => item.Password)
                                </td>
                                <td class="  sorting_1">
                                    @Html.DisplayFor(modelItem => item.Phone)
                                </td>
                                <td class="  sorting_1">
                                    @Html.DisplayFor(modelItem => item.DOB)
                                </td>

                                <td class="center ">
                                    <a class="btn btn-success" href="#">
                                        <i class="halflings-icon white zoom-in"></i>
                                    </a>
                                    <a class="btn btn-info" href="#">
                                        <i class="halflings-icon white edit"></i>
                                    </a>
                                    <a class="btn btn-danger" href="#">
                                        <i class="halflings-icon white trash"></i>
                                    </a>
                                </td>
                            </tr>
                        }



                    </tbody>
                </table>
                <div class="row-fluid">
                    <div class="span12">
                        <div id="DataTables_Table_01_info" class="dataTables_info">Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</div>
                    </div>
                    <div class="span12 center">
                        <div class="dataTables_paginate paging_bootstrap pagination">
                           @Html.PagedListPager(Model, page => Url.Action("Index", new { page, }), new  PagedListRenderOptions{
                        LinkToNextPageFormat="Next >>",
                        LinkToPreviousPageFormat = "<< Previous"
                      }) 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/span-->

</div><!--/row-->
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@*<table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DOB)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adress)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DOB)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Adress)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.CustomerID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.CustomerID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.CustomerID })
                </td>
            </tr>
        }

    </table>*@